# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_scrap', '0003_auto_20170909_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
                ('userPhoto', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(default='')),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
