# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_scrap', '0004_gameuser_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuser',
            name='userPhoto',
            field=models.ImageField(upload_to=''),
        ),
    ]
